export PS1="\n\n\n\u@\h | \@ \d | \w\n>>> "
export PATH=/usr/local/mysql/bin:$PATH

alias irc="ssh -p1239 shabren@fltt.us"
alias lug="ssh -C shabren@short.csc.ncsu.edu"
alias navy="ssh root@10.18.0.8"
alias yeager="ssh root@10.18.0.2"
alias hpux3="ssh -X root@10.18.0.61"
alias ls="ls -alsGh"
alias bell="ssh -X root@10.18.0.10"
alias glenn="ssh -X root@10.18.0.11"
alias runserv="python manage.py runserver"
alias mc="ssh -p1239 shabren@mc.shabren.com"
alias proxywork="ssh root@git.xvt.com -ND "
alias sbnet="ssh u40765419@stephenbryant.net"
